### ISSUE TITLE
When using the --ubuntu option for `docker/up.sh` the nodes are still running debian

### ISSUE THREAD

**Issue by siyopao** [jepsen-io/jepsen#360]
I found what I think is a small problem with Dockerized Jepsen. It seems that there may be a problem with merging Dockerfiles and using `extends`. Here is a small sample of what happens when I run:

```bash
docker-compose -f docker-compose.yml -f docker-compose.ubuntu.yml config
```

(which is the order used in `up.sh`) I get:

```yaml
n5:
    build:
      context: /Users/xxx/jepsen/docker/node
    container_name: jepsen-n5
    environment:
      AUTHORIZED_KEYS: ...
      ROOT_PASS: root
    hostname: n5
    privileged: true
node:
    build:
      context: /Users/xxx/jepsen/docker/node
      dockerfile: Dockerfile-ubuntu
    container_name: jepsen-node
    environment:
      AUTHORIZED_KEYS: ...
      ROOT_PASS: root
    privileged: true
version: '2.0'
...
```

So node gets the correct value for dockerfile, but anything that extends node does not. I suppose this can be fixed easily by removing `extends`. I am happy to create a PR if it helps.
