### ISSUE TITLE
bin/up logs out on Pop!_OS

### ISSUE THREAD

**Issue by m1l4n54v1c** [jepsen-io/jepsen#506]
Hi,

I'm trying to run jepsen docker setup on Pop!_OS:

```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
Whenever I run `bin/up` I get logged out. Containers are created and started, but as soon as all of them are started I get logged out. I'm unable to log in, so I need to restart the machine. After the next login, I'm able to start the control container using `docker container start`, but starting any of the `node` containers gets me logged out again. After the next login, I'm able to start all containers and everything works as expected.

I was able to track down that starting containers in `privileged mode` creates this issue. After tweaking docker-compose template to create docker-compose file without privileged mode (but mapping volumes with - "/sys/fs/cgroup:/sys/fs/cgroup:ro") jepsen is able to start without any logging out / restarting.
Of course, without priveleged mode, it is not possible to run nemesis, so this is not an option.

However, running `jgoerzen/debian-base-standard` in privileged mode alone using
```
docker run -td --stop-signal=SIGRTMIN+3 \
  --tmpfs /run:size=100M --tmpfs /run/lock:size=100M \
  -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --name=name --privileged jgoerzen/debian-base-whatever
```
is not a problem.

One colleague of mine, who is using the same OS, tried running jepsen and the same happens. On Windows WSL and Mac_OS, everything works fine.

Cheers,
Milan

**Comment by aphyr** [comment]
Oof. I'm afraid I don't know anything about Pop! OS--and I'm really not a Docker expert either. If you can figure out how to get rid of privileged mode and still retain a full init system and nemeses, I'd love to see that patch. In the meantime, one workaround might be to try running LXC containers--see doc/lxc.md for a guide on how to do that on Debian.

**Comment by m1l4n54v1c** [comment]
Thanks for a quick response! I'll let you know if I find a solution.

**Comment by m1l4n54v1c** [comment]
Hi, I finally found some time to work on this. Aaaand was able to fix it (apparently). What was missing from the previous template file was the network admin capability - what nemesis needs to "mess" with the network. Long story short, db nodes do not need `privileged` mode anymore, and this is how the template for docker-compose looks like now:

```
version: '3.7'
x-node:
  &default-node
  build: ./node
  env_file: ./secret/node.env
  secrets:
    - authorized_keys
  tty: true
  tmpfs:
    - /run:size=100M
    - /run/lock:size=100M
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"      # <--------------------------
    - "jepsen-shared:/var/jepsen/shared"
  networks:
    - jepsen
  cap_add:                   # <--------------------------
    - NET_ADMIN         # <--------------------------
  ports:
    - ${JEPSEN_PORT:-22}

...
```
Didn't try it on different OSes. Let me know if this is worth creating a PR.
